;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.demo.gallery.app
  "The gallery as an app: every scene behind a two-level menu.

  The registry namespace loads every scene and draw namespace and holds the
  scenes and categories. The menu itself is raylib-ios's gallery shell, which
  takes them as data."
  (:require
   [net.b12n.raylib-ios.demo.gallery.registry :as registry]
   [net.b12n.raylib-ios.gallery :as gallery]))

(defn -main [& _]
  (gallery/run! registry/gallery))
