;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.demo.gallery.app
  "The gallery as an app: every scene behind a two-level menu.

  The registry namespace loads every scene and draw namespace. The menu itself is
  raylib-ios's gallery shell."
  (:require
   [net.b12n.raylib-ios.demo.gallery.registry]
   [net.b12n.raylib-ios.gallery :as gallery]))

(defn -main [& _]
  (gallery/-main))
