;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.demo.gallery.registry
  "Every scene in the gallery, and the categories that group them.

  Requiring this namespace loads every scene and every draw namespace, so each
  draw-scene! method is registered. Hello is raylib-ios's own and comes from
  that dependency; the rest come from the sub-projects listed in demos.edn."
  (:require
   [net.b12n.raylib-ios.scenes.align :as align]
   [net.b12n.raylib-ios.scenes.align.draw]
   [net.b12n.raylib-ios.scenes.analog :as analog]
   [net.b12n.raylib-ios.scenes.analog.draw]
   [net.b12n.raylib-ios.scenes.angles :as angles]
   [net.b12n.raylib-ios.scenes.angles.draw]
   [net.b12n.raylib-ios.scenes.asteroids :as asteroids]
   [net.b12n.raylib-ios.scenes.asteroids.draw]
   [net.b12n.raylib-ios.scenes.automata :as automata]
   [net.b12n.raylib-ios.scenes.automata.draw]
   [net.b12n.raylib-ios.scenes.balls :as balls]
   [net.b12n.raylib-ios.scenes.balls.draw]
   [net.b12n.raylib-ios.scenes.bars :as bars]
   [net.b12n.raylib-ios.scenes.bars.draw]
   [net.b12n.raylib-ios.scenes.bezier :as bezier]
   [net.b12n.raylib-ios.scenes.bezier.draw]
   [net.b12n.raylib-ios.scenes.bgscroll :as bgscroll]
   [net.b12n.raylib-ios.scenes.bgscroll.draw]
   [net.b12n.raylib-ios.scenes.billboard :as billboard]
   [net.b12n.raylib-ios.scenes.billboard.draw]
   [net.b12n.raylib-ios.scenes.blendmodes :as blendmodes]
   [net.b12n.raylib-ios.scenes.blendmodes.draw]
   [net.b12n.raylib-ios.scenes.blendparticles :as blendparticles]
   [net.b12n.raylib-ios.scenes.blendparticles.draw]
   [net.b12n.raylib-ios.scenes.boids :as boids]
   [net.b12n.raylib-ios.scenes.boids.draw]
   [net.b12n.raylib-ios.scenes.bounce :as bounce]
   [net.b12n.raylib-ios.scenes.bounce.draw]
   [net.b12n.raylib-ios.scenes.boxcollide :as boxcollide]
   [net.b12n.raylib-ios.scenes.boxcollide.draw]
   [net.b12n.raylib-ios.scenes.breakout :as breakout]
   [net.b12n.raylib-ios.scenes.breakout.draw]
   [net.b12n.raylib-ios.scenes.bullets :as bullets]
   [net.b12n.raylib-ios.scenes.bullets.draw]
   [net.b12n.raylib-ios.scenes.bunnymark :as bunnymark]
   [net.b12n.raylib-ios.scenes.bunnymark.draw]
   [net.b12n.raylib-ios.scenes.camera2d :as camera2d]
   [net.b12n.raylib-ios.scenes.camera2d.draw]
   [net.b12n.raylib-ios.scenes.camera3d :as camera3d]
   [net.b12n.raylib-ios.scenes.camera3d.draw]
   [net.b12n.raylib-ios.scenes.camerazoom :as camerazoom]
   [net.b12n.raylib-ios.scenes.camerazoom.draw]
   [net.b12n.raylib-ios.scenes.clipbox :as clipbox]
   [net.b12n.raylib-ios.scenes.clipbox.draw]
   [net.b12n.raylib-ios.scenes.clock :as clock]
   [net.b12n.raylib-ios.scenes.clock.draw]
   [net.b12n.raylib-ios.scenes.clockgrid :as clockgrid]
   [net.b12n.raylib-ios.scenes.clockgrid.draw]
   [net.b12n.raylib-ios.scenes.collision :as collision]
   [net.b12n.raylib-ios.scenes.collision.draw]
   [net.b12n.raylib-ios.scenes.colorwheel :as colorwheel]
   [net.b12n.raylib-ios.scenes.colorwheel.draw]
   [net.b12n.raylib-ios.scenes.dashed :as dashed]
   [net.b12n.raylib-ios.scenes.dashed.draw]
   [net.b12n.raylib-ios.scenes.deltatime :as deltatime]
   [net.b12n.raylib-ios.scenes.deltatime.draw]
   [net.b12n.raylib-ios.scenes.dirbillboard :as dirbillboard]
   [net.b12n.raylib-ios.scenes.dirbillboard.draw]
   [net.b12n.raylib-ios.scenes.doom :as doom]
   [net.b12n.raylib-ios.scenes.doom.draw]
   [net.b12n.raylib-ios.scenes.easings :as easings]
   [net.b12n.raylib-ios.scenes.easings.draw]
   [net.b12n.raylib-ios.scenes.easingsbox :as easingsbox]
   [net.b12n.raylib-ios.scenes.easingsbox.draw]
   [net.b12n.raylib-ios.scenes.easingstestbed :as easingstestbed]
   [net.b12n.raylib-ios.scenes.easingstestbed.draw]
   [net.b12n.raylib-ios.scenes.ellipses :as ellipses]
   [net.b12n.raylib-ios.scenes.ellipses.draw]
   [net.b12n.raylib-ios.scenes.epicycles :as epicycles]
   [net.b12n.raylib-ios.scenes.epicycles.draw]
   [net.b12n.raylib-ios.scenes.fan :as fan]
   [net.b12n.raylib-ios.scenes.fan.draw]
   [net.b12n.raylib-ios.scenes.fbrender :as fbrender]
   [net.b12n.raylib-ios.scenes.fbrender.draw]
   [net.b12n.raylib-ios.scenes.fireworks :as fireworks]
   [net.b12n.raylib-ios.scenes.fireworks.draw]
   [net.b12n.raylib-ios.scenes.flappy-bird :as flappy-bird]
   [net.b12n.raylib-ios.scenes.flappy-bird.draw]
   [net.b12n.raylib-ios.scenes.flowfield :as flowfield]
   [net.b12n.raylib-ios.scenes.flowfield.draw]
   [net.b12n.raylib-ios.scenes.fogofwar :as fogofwar]
   [net.b12n.raylib-ios.scenes.fogofwar.draw]
   [net.b12n.raylib-ios.scenes.following-eyes :as following-eyes]
   [net.b12n.raylib-ios.scenes.following-eyes.draw]
   [net.b12n.raylib-ios.scenes.fontsizes :as fontsizes]
   [net.b12n.raylib-ios.scenes.fontsizes.draw]
   [net.b12n.raylib-ios.scenes.formattext :as formattext]
   [net.b12n.raylib-ios.scenes.formattext.draw]
   [net.b12n.raylib-ios.scenes.fpcamera :as fpcamera]
   [net.b12n.raylib-ios.scenes.fpcamera.draw]
   [net.b12n.raylib-ios.scenes.fpmaze :as fpmaze]
   [net.b12n.raylib-ios.scenes.fpmaze.draw]
   [net.b12n.raylib-ios.scenes.freecam :as freecam]
   [net.b12n.raylib-ios.scenes.freecam.draw]
   [net.b12n.raylib-ios.scenes.game2048 :as game2048]
   [net.b12n.raylib-ios.scenes.game2048.draw]
   [net.b12n.raylib-ios.scenes.geoshapes :as geoshapes]
   [net.b12n.raylib-ios.scenes.geoshapes.draw]
   [net.b12n.raylib-ios.scenes.gestures :as gestures]
   [net.b12n.raylib-ios.scenes.gestures.draw]
   [net.b12n.raylib-ios.scenes.gradient :as gradient]
   [net.b12n.raylib-ios.scenes.gradient.draw]
   [net.b12n.raylib-ios.scenes.helitorus :as helitorus]
   [net.b12n.raylib-ios.scenes.helitorus.draw]
   [net.b12n.raylib-ios.scenes.hello :as hello]
   [net.b12n.raylib-ios.scenes.hello.draw]
   [net.b12n.raylib-ios.scenes.hilbert :as hilbert]
   [net.b12n.raylib-ios.scenes.hilbert.draw]
   [net.b12n.raylib-ios.scenes.huewheel :as huewheel]
   [net.b12n.raylib-ios.scenes.huewheel.draw]
   [net.b12n.raylib-ios.scenes.inlinestyle :as inlinestyle]
   [net.b12n.raylib-ios.scenes.inlinestyle.draw]
   [net.b12n.raylib-ios.scenes.invaders :as invaders]
   [net.b12n.raylib-ios.scenes.invaders.draw]
   [net.b12n.raylib-ios.scenes.kaleidoscope :as kaleidoscope]
   [net.b12n.raylib-ios.scenes.kaleidoscope.draw]
   [net.b12n.raylib-ios.scenes.letterbox :as letterbox]
   [net.b12n.raylib-ios.scenes.letterbox.draw]
   [net.b12n.raylib-ios.scenes.life :as life]
   [net.b12n.raylib-ios.scenes.life.draw]
   [net.b12n.raylib-ios.scenes.logo :as logo]
   [net.b12n.raylib-ios.scenes.logo.draw]
   [net.b12n.raylib-ios.scenes.logoanim :as logoanim]
   [net.b12n.raylib-ios.scenes.logoanim.draw]
   [net.b12n.raylib-ios.scenes.lorenz :as lorenz]
   [net.b12n.raylib-ios.scenes.lorenz.draw]
   [net.b12n.raylib-ios.scenes.lsystem :as lsystem]
   [net.b12n.raylib-ios.scenes.lsystem.draw]
   [net.b12n.raylib-ios.scenes.magnify :as magnify]
   [net.b12n.raylib-ios.scenes.magnify.draw]
   [net.b12n.raylib-ios.scenes.minesweeper :as minesweeper]
   [net.b12n.raylib-ios.scenes.minesweeper.draw]
   [net.b12n.raylib-ios.scenes.mousepaint :as mousepaint]
   [net.b12n.raylib-ios.scenes.mousepaint.draw]
   [net.b12n.raylib-ios.scenes.multitouch :as multitouch]
   [net.b12n.raylib-ios.scenes.multitouch.draw]
   [net.b12n.raylib-ios.scenes.npatch :as npatch]
   [net.b12n.raylib-ios.scenes.npatch.draw]
   [net.b12n.raylib-ios.scenes.nudge :as nudge]
   [net.b12n.raylib-ios.scenes.nudge.draw]
   [net.b12n.raylib-ios.scenes.ortho :as ortho]
   [net.b12n.raylib-ios.scenes.ortho.draw]
   [net.b12n.raylib-ios.scenes.outlines :as outlines]
   [net.b12n.raylib-ios.scenes.outlines.draw]
   [net.b12n.raylib-ios.scenes.pacman :as pacman]
   [net.b12n.raylib-ios.scenes.pacman.draw]
   [net.b12n.raylib-ios.scenes.palette :as palette]
   [net.b12n.raylib-ios.scenes.palette.draw]
   [net.b12n.raylib-ios.scenes.particles :as particles]
   [net.b12n.raylib-ios.scenes.particles.draw]
   [net.b12n.raylib-ios.scenes.pendulum :as pendulum]
   [net.b12n.raylib-ios.scenes.pendulum.draw]
   [net.b12n.raylib-ios.scenes.penrose :as penrose]
   [net.b12n.raylib-ios.scenes.penrose.draw]
   [net.b12n.raylib-ios.scenes.picking :as picking]
   [net.b12n.raylib-ios.scenes.picking.draw]
   [net.b12n.raylib-ios.scenes.piechart :as piechart]
   [net.b12n.raylib-ios.scenes.piechart.draw]
   [net.b12n.raylib-ios.scenes.pixelperfect :as pixelperfect]
   [net.b12n.raylib-ios.scenes.pixelperfect.draw]
   [net.b12n.raylib-ios.scenes.platformer :as platformer]
   [net.b12n.raylib-ios.scenes.platformer.draw]
   [net.b12n.raylib-ios.scenes.pointcloud :as pointcloud]
   [net.b12n.raylib-ios.scenes.pointcloud.draw]
   [net.b12n.raylib-ios.scenes.pong :as pong]
   [net.b12n.raylib-ios.scenes.pong.draw]
   [net.b12n.raylib-ios.scenes.randomvalues :as randomvalues]
   [net.b12n.raylib-ios.scenes.randomvalues.draw]
   [net.b12n.raylib-ios.scenes.rawdata :as rawdata]
   [net.b12n.raylib-ios.scenes.rawdata.draw]
   [net.b12n.raylib-ios.scenes.rectbounds :as rectbounds]
   [net.b12n.raylib-ios.scenes.rectbounds.draw]
   [net.b12n.raylib-ios.scenes.rendertex :as rendertex]
   [net.b12n.raylib-ios.scenes.rendertex.draw]
   [net.b12n.raylib-ios.scenes.resize :as resize]
   [net.b12n.raylib-ios.scenes.resize.draw]
   [net.b12n.raylib-ios.scenes.ring :as ring]
   [net.b12n.raylib-ios.scenes.ring.draw]
   [net.b12n.raylib-ios.scenes.rlgltriangle :as rlgltriangle]
   [net.b12n.raylib-ios.scenes.rlgltriangle.draw]
   [net.b12n.raylib-ios.scenes.rotcube :as rotcube]
   [net.b12n.raylib-ios.scenes.rotcube.draw]
   [net.b12n.raylib-ios.scenes.rounded :as rounded]
   [net.b12n.raylib-ios.scenes.rounded.draw]
   [net.b12n.raylib-ios.scenes.screenbuf :as screenbuf]
   [net.b12n.raylib-ios.scenes.screenbuf.draw]
   [net.b12n.raylib-ios.scenes.screens :as screens]
   [net.b12n.raylib-ios.scenes.screens.draw]
   [net.b12n.raylib-ios.scenes.sector :as sector]
   [net.b12n.raylib-ios.scenes.sector.draw]
   [net.b12n.raylib-ios.scenes.sequence :as sequence]
   [net.b12n.raylib-ios.scenes.sequence.draw]
   [net.b12n.raylib-ios.scenes.shapes :as shapes]
   [net.b12n.raylib-ios.scenes.shapes.draw]
   [net.b12n.raylib-ios.scenes.snake :as snake]
   [net.b12n.raylib-ios.scenes.snake.draw]
   [net.b12n.raylib-ios.scenes.solarsystem :as solarsystem]
   [net.b12n.raylib-ios.scenes.solarsystem.draw]
   [net.b12n.raylib-ios.scenes.spheres :as spheres]
   [net.b12n.raylib-ios.scenes.spheres.draw]
   [net.b12n.raylib-ios.scenes.spincubes :as spincubes]
   [net.b12n.raylib-ios.scenes.spincubes.draw]
   [net.b12n.raylib-ios.scenes.spirograph :as spirograph]
   [net.b12n.raylib-ios.scenes.spirograph.draw]
   [net.b12n.raylib-ios.scenes.splines :as splines]
   [net.b12n.raylib-ios.scenes.splines.draw]
   [net.b12n.raylib-ios.scenes.split3d :as split3d]
   [net.b12n.raylib-ios.scenes.split3d.draw]
   [net.b12n.raylib-ios.scenes.splitscreen :as splitscreen]
   [net.b12n.raylib-ios.scenes.splitscreen.draw]
   [net.b12n.raylib-ios.scenes.spriteanim :as spriteanim]
   [net.b12n.raylib-ios.scenes.spriteanim.draw]
   [net.b12n.raylib-ios.scenes.spritebutton :as spritebutton]
   [net.b12n.raylib-ios.scenes.spritebutton.draw]
   [net.b12n.raylib-ios.scenes.spritestack :as spritestack]
   [net.b12n.raylib-ios.scenes.spritestack.draw]
   [net.b12n.raylib-ios.scenes.srcrec :as srcrec]
   [net.b12n.raylib-ios.scenes.srcrec.draw]
   [net.b12n.raylib-ios.scenes.starfield :as starfield]
   [net.b12n.raylib-ios.scenes.starfield.draw]
   [net.b12n.raylib-ios.scenes.stars :as stars]
   [net.b12n.raylib-ios.scenes.stars.draw]
   [net.b12n.raylib-ios.scenes.strings :as strings]
   [net.b12n.raylib-ios.scenes.strings.draw]
   [net.b12n.raylib-ios.scenes.strip :as strip]
   [net.b12n.raylib-ios.scenes.strip.draw]
   [net.b12n.raylib-ios.scenes.survivors :as survivors]
   [net.b12n.raylib-ios.scenes.survivors.draw]
   [net.b12n.raylib-ios.scenes.tesseract :as tesseract]
   [net.b12n.raylib-ios.scenes.tesseract.draw]
   [net.b12n.raylib-ios.scenes.tetris :as tetris]
   [net.b12n.raylib-ios.scenes.tetris.draw]
   [net.b12n.raylib-ios.scenes.texcube :as texcube]
   [net.b12n.raylib-ios.scenes.texcube.draw]
   [net.b12n.raylib-ios.scenes.texcurve :as texcurve]
   [net.b12n.raylib-ios.scenes.texcurve.draw]
   [net.b12n.raylib-ios.scenes.texpoly :as texpoly]
   [net.b12n.raylib-ios.scenes.texpoly.draw]
   [net.b12n.raylib-ios.scenes.texproc :as texproc]
   [net.b12n.raylib-ios.scenes.texproc.draw]
   [net.b12n.raylib-ios.scenes.textiling :as textiling]
   [net.b12n.raylib-ios.scenes.textiling.draw]
   [net.b12n.raylib-ios.scenes.toplights :as toplights]
   [net.b12n.raylib-ios.scenes.toplights.draw]
   [net.b12n.raylib-ios.scenes.touch-trail :as touch-trail]
   [net.b12n.raylib-ios.scenes.touch-trail.draw]
   [net.b12n.raylib-ios.scenes.touchball :as touchball]
   [net.b12n.raylib-ios.scenes.touchball.draw]
   [net.b12n.raylib-ios.scenes.tree :as tree]
   [net.b12n.raylib-ios.scenes.tree.draw]
   [net.b12n.raylib-ios.scenes.undoredo :as undoredo]
   [net.b12n.raylib-ios.scenes.undoredo.draw]
   [net.b12n.raylib-ios.scenes.unitcircle :as unitcircle]
   [net.b12n.raylib-ios.scenes.unitcircle.draw]
   [net.b12n.raylib-ios.scenes.vecangle :as vecangle]
   [net.b12n.raylib-ios.scenes.vecangle.draw]
   [net.b12n.raylib-ios.scenes.virtualpad :as virtualpad]
   [net.b12n.raylib-ios.scenes.virtualpad.draw]
   [net.b12n.raylib-ios.scenes.voxel :as voxel]
   [net.b12n.raylib-ios.scenes.voxel.draw]
   [net.b12n.raylib-ios.scenes.vpscaling :as vpscaling]
   [net.b12n.raylib-ios.scenes.vpscaling.draw]
   [net.b12n.raylib-ios.scenes.wavecubes :as wavecubes]
   [net.b12n.raylib-ios.scenes.wavecubes.draw]
   [net.b12n.raylib-ios.scenes.wheelbox :as wheelbox]
   [net.b12n.raylib-ios.scenes.wheelbox.draw]
   [net.b12n.raylib-ios.scenes.wireframes :as wireframes]
   [net.b12n.raylib-ios.scenes.wireframes.draw]
   [net.b12n.raylib-ios.scenes.worldscreen :as worldscreen]
   [net.b12n.raylib-ios.scenes.worldscreen.draw]
   [net.b12n.raylib-ios.scenes.writing :as writing]
   [net.b12n.raylib-ios.scenes.writing.draw]
   [net.b12n.raylib-ios.scenes.yawpitchroll :as yawpitchroll]
   [net.b12n.raylib-ios.scenes.yawpitchroll.draw]))

(def scenes
  [(following-eyes/scene)
   (touch-trail/scene)
   (flappy-bird/scene)
   (spirograph/scene)
   (kaleidoscope/scene)
   (fireworks/scene)
   (penrose/scene)
   (boids/scene)
   (pendulum/scene)
   (epicycles/scene)
   (hilbert/scene)
   (tree/scene)
   (stars/scene)
   (lsystem/scene)
   (flowfield/scene)
   (lorenz/scene)
   (tesseract/scene)
   (life/scene)
   (automata/scene)
   (colorwheel/scene)
   (unitcircle/scene)
   (clock/scene)
   (piechart/scene)
   (logoanim/scene)
   (easings/scene)
   (angles/scene)
   (writing/scene)
   (balls/scene)
   (sequence/scene)
   (bullets/scene)
   (collision/scene)
   (dashed/scene)
   (multitouch/scene)
   (analog/scene)
   (clockgrid/scene)
   (sector/scene)
   (palette/scene)
   (gradient/scene)
   (ring/scene)
   (splines/scene)
   (rounded/scene)
   (vecangle/scene)
   (bars/scene)
   (bezier/scene)
   (fan/scene)
   (clipbox/scene)
   (resize/scene)
   (align/scene)
   (deltatime/scene)
   (randomvalues/scene)
   (formattext/scene)
   (strip/scene)
   (touchball/scene)
   (rlgltriangle/scene)
   (particles/scene)
   (breakout/scene)
   (bounce/scene)
   (snake/scene)
   (game2048/scene)
   (minesweeper/scene)
   (pong/scene)
   (invaders/scene)
   (tetris/scene)
   (asteroids/scene)
   (virtualpad/scene)
   (starfield/scene)
   (easingsbox/scene)
   (easingstestbed/scene)
   (rectbounds/scene)
   (huewheel/scene)
   (logo/scene)
   (fontsizes/scene)
   (inlinestyle/scene)
   (outlines/scene)
   (shapes/scene)
   (ellipses/scene)
   (screens/scene)
   (survivors/scene)
   (pacman/scene)
   (hello/scene)
   (nudge/scene)
   (wheelbox/scene)
   (undoredo/scene)
   (strings/scene)
   (camera2d/scene)
   (camerazoom/scene)
   (platformer/scene)
   (splitscreen/scene)
   (gestures/scene)
   (helitorus/scene)
   (rotcube/scene)
   (camera3d/scene)
   (ortho/scene)
   (spincubes/scene)
   (worldscreen/scene)
   (wireframes/scene)
   (freecam/scene)
   (yawpitchroll/scene)
   (boxcollide/scene)
   (picking/scene)
   (wavecubes/scene)
   (solarsystem/scene)
   (pointcloud/scene)
   (fpcamera/scene)
   (fpmaze/scene)
   (split3d/scene)
   (spheres/scene)
   (bunnymark/scene)
   (bgscroll/scene)
   (spritestack/scene)
   (pixelperfect/scene)
   (vpscaling/scene)
   (letterbox/scene)
   (fogofwar/scene)
   (blendmodes/scene)
   (blendparticles/scene)
   (billboard/scene)
   (dirbillboard/scene)
   (texcube/scene)
   (geoshapes/scene)
   (voxel/scene)
   (doom/scene)
   (textiling/scene)
   (srcrec/scene)
   (spritebutton/scene)
   (npatch/scene)
   (texpoly/scene)
   (texproc/scene)
   (spriteanim/scene)
   (texcurve/scene)
   (rendertex/scene)
   (fbrender/scene)
   (mousepaint/scene)
   (magnify/scene)
   (toplights/scene)
   (rawdata/scene)
   (screenbuf/scene)])

(def categories
  [{:id :generative
    :title "Generative"
    :scenes [:spirograph :kaleidoscope :fireworks :penrose :epicycles :flowfield
             :lorenz :life :bullets]}
   {:id :fractals
    :title "Fractals"
    :scenes [:hilbert :tree :lsystem :automata]}
   {:id :toys
    :title "Toys"
    :scenes [:following-eyes :touch-trail :boids :pendulum :stars :tesseract
             :colorwheel :unitcircle :clock :piechart :logoanim :easings
             :angles :writing :balls :sequence :collision :dashed
             :multitouch :analog :clockgrid :sector :palette :gradient
             :ring :splines :rounded :vecangle :bars :bezier
             :fan :clipbox :resize :align :deltatime :randomvalues
             :formattext :strip :touchball :rlgltriangle :particles :bounce
             :virtualpad :starfield :easingsbox :easingstestbed :rectbounds :huewheel
             :logo :fontsizes :inlinestyle :outlines :shapes :ellipses
             :screens :hello :nudge :wheelbox :undoredo :strings
             :camera2d :camerazoom :platformer :splitscreen :gestures :helitorus
             :rotcube :camera3d :ortho :spincubes :worldscreen :wireframes
             :freecam :yawpitchroll :boxcollide :picking :wavecubes :solarsystem
             :pointcloud :fpcamera :fpmaze :split3d :spheres :bunnymark
             :bgscroll :spritestack :pixelperfect :vpscaling :letterbox :fogofwar
             :blendmodes :blendparticles :billboard :dirbillboard :texcube :geoshapes
             :voxel :doom :textiling :srcrec :spritebutton :npatch
             :texpoly :texproc :spriteanim :texcurve :rendertex :fbrender
             :mousepaint :magnify :toplights :rawdata :screenbuf]}
   {:id :games
    :title "Games"
    :scenes [:flappy-bird :breakout :snake :game2048 :minesweeper :pong
             :invaders :tetris :asteroids :survivors :pacman]}])
