;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.piechart.app
  "Pie Chart as an app of its own: the scene full screen, with no menu and no Back."
  (:require
   [net.b12n.raylib-ios.runner :as runner]
   [net.b12n.raylib-ios.scenes.piechart :as scene]
   [net.b12n.raylib-ios.scenes.piechart.draw]))

(defn -main [& _]
  (runner/run! (scene/scene)))
