;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.split3d.live
  "3D Split Screen as a dev app: the same scene, with an nREPL listening on the phone."
  (:require
   [net.b12n.raylib-ios.runner.live :as live]
   [net.b12n.raylib-ios.scenes.split3d :as scene]
   [net.b12n.raylib-ios.scenes.split3d.draw]))

(defn -main [& _]
  (live/live-run! (scene/scene)))
