;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.deltatime.live
  "Delta Time as a dev app: the same scene, with an nREPL listening on the phone."
  (:require
   [net.b12n.raylib-ios.runner.live :as live]
   [net.b12n.raylib-ios.scenes.deltatime :as scene]
   [net.b12n.raylib-ios.scenes.deltatime.draw]))

(defn -main [& _]
  (live/live-run! (scene/scene)))
