;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.formattext.app
  "Formatted Text as an app of its own: the scene full screen, with no menu and no Back."
  (:require
   [net.b12n.raylib-ios.runner :as runner]
   [net.b12n.raylib-ios.scenes.formattext :as scene]
   [net.b12n.raylib-ios.scenes.formattext.draw]))

(defn -main [& _]
  (runner/run! (scene/scene)))
