;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.fpcamera.live
  "First-Person Camera as a dev app: the same scene, with an nREPL listening on the phone."
  (:require
   [net.b12n.raylib-ios.runner.live :as live]
   [net.b12n.raylib-ios.scenes.fpcamera :as scene]
   [net.b12n.raylib-ios.scenes.fpcamera.draw]))

(defn -main [& _]
  (live/live-run! (scene/scene)))
