;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.doom.live
  "Doom-like Raycaster as a dev app: the same scene, with an nREPL listening on the phone."
  (:require
   [net.b12n.raylib-ios.runner.live :as live]
   [net.b12n.raylib-ios.scenes.doom :as scene]
   [net.b12n.raylib-ios.scenes.doom.draw]))

(defn -main [& _]
  (live/live-run! (scene/scene)))
