;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.vpscaling.live
  "Viewport Scaling as a dev app: the same scene, with an nREPL listening on the phone."
  (:require
   [net.b12n.raylib-ios.runner.live :as live]
   [net.b12n.raylib-ios.scenes.vpscaling :as scene]
   [net.b12n.raylib-ios.scenes.vpscaling.draw]))

(defn -main [& _]
  (live/live-run! (scene/scene)))
