(ns gen
  "Rebuild the files that list every scene (`bb gen`).

  demos.edn is the list, edited by hand. From it and the scene sources on disk
  this writes:

  - deps.edn                          one alias per scene, plus :check and :test
  - src/.../demo/check.clj            requires every app namespace
  - bb.edn, between its BEGIN/END markers   one task per scene
  - <name>/deps.edn, <name>/bb.edn    each scene's sub-project
  - <name>/src/.../scenes/<x>/app.clj and live.clj
                                      the single-scene apps (release and nREPL)
  - gallery/deps.edn, gallery/bb.edn
  - gallery/src/.../gallery/registry.clj, app.clj and live.clj
                                      the scenes vector, the categories, the app
  - docs/guide/demos.md               the site's gallery

  Each scene's sources, draws, tests and docs page are hand-owned: gen only
  reads them. A scene's dependencies on other scenes (outlines uses rounded)
  are read from its ns forms, so a new `:require` shows up in deps.edn on the
  next run.

  Usage: bb gen [--check]
  --check writes nothing and exits 1 if any of those files is out of date."
  (:require
   [babashka.fs :as fs]
   [clojure.edn :as edn]
   [clojure.string :as str]
   [clojure.walk :as walk]))

(def root (str (fs/parent (fs/parent (fs/absolutize *file*)))))

(def repo-url "https://github.com/jlt-commons/raylib-ios-demo")

(def scene-ns-prefix "net.b12n.raylib-ios.scenes.")
(def scene-path "src/net/b12n/raylib_ios/scenes")
(def demo-ns "net.b12n.raylib-ios.demo")
(def demo-path "net/b12n/raylib_ios/demo")

;; The gallery's categories, in menu order. demos.edn's :category is the id.
(def categories
  [["generative" "Generative"]
   ["fractals" "Fractals"]
   ["toys" "Toys"]
   ["games" "Games"]])

;; The hand-written tasks in bb.edn. A scene with one of these names gets no task
;; of its own, though `bb run <name>` still reaches it.
(def fixed-tasks
  #{"info" "list" "run" "live" "test" "check" "lint" "lint:strict" "doctor" "gen"
    "gallery" "gallery:live"})

;; Directories at the top level that are not scenes.
(def non-scene-dirs #{"common" "docs" "gallery" "scripts" "src" "tools"})

(def generated-header ";; Generated by `bb gen` from demos.edn. Edits here are overwritten.\n")

(def begin-marker "  ;; BEGIN per-scene tasks, generated by `bb gen`\n")
(def end-marker "  ;; END per-scene tasks\n")

(defn- seg [entry] (name (:id entry)))
(defn- stem [entry] (str/replace (seg entry) "-" "_"))
(defn- scene-ns [entry] (str scene-ns-prefix (seg entry)))
(defn- app-ns [entry] (str (scene-ns entry) ".app"))
(defn- live-ns [entry] (str (scene-ns entry) ".live"))
(defn- dep-key [name] (str "net.b12n.raylib-ios-demo/" name))
(defn- scene-dir [entry] (str (:name entry) "/" scene-path "/" (stem entry)))
(defn- projects [entries] (remove :home entries))

(defn- source-files
  "Every .clj/.cljc under the scene's src directory that gen did not write."
  [entry]
  (for [f (fs/glob (fs/file root (:name entry) "src") "**.{clj,cljc}")
        :let [n (str (fs/file-name f))]
        :when (not (#{"app.clj" "live.clj"} n))]
    (str f)))

(defn- ns-form-symbols [file]
  (try
    (let [form (read-string {:read-cond :allow
                             :features #{:clj}} (slurp file))
          found (atom #{})]
      (walk/postwalk (fn [x] (when (symbol? x) (swap! found conj (str x))) x) form)
      @found)
    (catch Exception e
      (throw (ex-info (str "gen could not read the ns form of " file ": " (ex-message e)) {})))))

(defn- scene-deps
  "The other scenes whose namespaces `entry`'s sources require, as entries,
  read from the ns forms (so a mention in a docstring does not count)."
  [entry by-seg]
  (->> (source-files entry)
       (mapcat ns-form-symbols)
       (keep #(second (re-find (re-pattern (str "^" (str/replace scene-ns-prefix "." "\\.") "([a-z0-9-]+)")) %)))
       distinct
       (remove #{(seg entry)})
       (keep by-seg)
       (remove :home)
       (sort-by :name)))

(defn- has-tests? [entry]
  (boolean (seq (fs/glob (fs/file root (:name entry) "test") "**_test.{clj,cljc}"))))

(defn- media-of
  "The scene's recording under docs/images, gif preferred, or nil."
  [entry]
  (first (for [ext ["gif" "png"]
               :when (fs/exists? (fs/file root "docs/images" (str (seg entry) "." ext)))]
           (str (seg entry) "." ext))))

;; --- deps.edn files

(defn- root-deps-edn [entries]
  (let [ps (projects entries)
        paths (fn [d] [(str d "/src") (str d "/test")])
        all-dirs (concat (map :name ps) ["gallery"])
        ;; four to a line, continuation lines under the first element
        quoted (fn [xs indent]
                 (str/join (str "\n" (apply str (repeat indent " ")))
                           (map #(str/join " " (map pr-str %)) (partition-all 4 xs))))
        test-paths (for [d all-dirs
                         p (paths d)
                         :when (or (str/ends-with? p "/src") (fs/exists? (fs/file root p)))]
                     p)
        scene-aliases (str/join "\n"
                                (for [e ps]
                                  (str "  :" (:name e) " {:extra-deps {" (dep-key (:name e)) " {:local/root " (pr-str (:name e)) "}}\n"
                                       "   " (str/join (repeat (count (:name e)) " ")) "  :main-opts [\"-m\" " (pr-str (app-ns e)) "]}")))]
    (str generated-header
         ";; Root of the raylib-ios-demo suite. Every scene is its own sub-project\n"
         ";; (<name>/deps.edn) and builds from there as a one-scene iOS app. gallery/ is\n"
         ";; the app holding all of them.\n"
         ";;\n"
         ";; The scene aliases carry each scene's classpath and its app entry point. They\n"
         ";; do not run on a desktop: -main hands the scene to UIKit. Build and install\n"
         ";; with `bb <name>`. `jolt -M:check` loads every app namespace with no\n"
         ";; window, and `jolt -M:test` (or `clojure -M:test`) runs every scene's tests.\n"
         ";; raylib-ios arrives through common/.\n"
         "{:jolt/min-version \"0.8.0\"\n"
         " :paths [\"src\"]\n"
         " :deps {net.b12n.raylib-ios-demo/common {:local/root \"common\"}}\n"
         " :aliases\n"
         " {:check {:extra-paths [" (quoted (map #(str % "/src") all-dirs) 24) "]\n"
         "          :main-opts [\"-m\" \"" demo-ns ".check\"]}\n"
         "\n"
         "  :test {:extra-paths [" (quoted test-paths 23) "]\n"
         "         :main-opts [\"-m\" \"" demo-ns ".test-runner\" \"--subprojects\"]}\n"
         "\n"
         scene-aliases "}}\n")))

(defn- scene-deps-edn [entry deps]
  (str generated-header
       "{:jolt/min-version \"0.8.0\"\n"
       " :paths [\"src\"]\n"
       " :deps {" (dep-key "common") " {:local/root \"../common\"}"
       (str/join (for [d deps] (str "\n        " (dep-key (:name d)) " {:local/root \"../" (:name d) "\"}")))
       "}\n"
       " :aliases\n"
       " {:run {:main-opts [\"-m\" \"" (app-ns entry) "\"]}\n"
       "  :live {:main-opts [\"-m\" \"" (live-ns entry) "\"]}"
       (when (has-tests? entry)
         (str "\n  :test {:extra-paths [\"test\"]\n"
              "         :main-opts [\"-m\" \"" demo-ns ".test-runner\" \"test\"]}"))
       "}}\n"))

(defn- gallery-deps-edn [entries]
  (let [ps (projects entries)]
    (str generated-header
         "{:jolt/min-version \"0.8.0\"\n"
         " :paths [\"src\"]\n"
         " :deps {" (dep-key "common") " {:local/root \"../common\"}"
         (str/join (for [e ps] (str "\n        " (dep-key (:name e)) " {:local/root \"../" (:name e) "\"}")))
         "}\n"
         " :aliases\n"
         " {:run {:main-opts [\"-m\" \"" demo-ns ".gallery.app\"]}\n"
         "  :live {:main-opts [\"-m\" \"" demo-ns ".gallery.live\"]}\n"
         "  :test {:extra-paths [\"test\"]\n"
         "         :main-opts [\"-m\" \"" demo-ns ".test-runner\" \"test\"]}}}\n")))

;; --- bb.edn files

(defn- scene-bb-edn [entry]
  (str generated-header
       ";; Run this scene from here with `bb run` or `bb live`, or from the repo root with\n"
       ";; `bb " (:name entry) "`. UDID names the phone: UDID=<hardware udid> bb run.\n"
       "{:paths [\"../scripts\"]\n"
       " :tasks\n"
       " {:requires ([ios-tools])\n"
       "  run {:doc " (pr-str (str "▶ " (:desc entry))) "\n"
       "       :override-builtin true\n"
       "       :task (ios-tools/exit-with (ios-tools/run! \".\" " (pr-str (app-ns entry)) "))}\n"
       "  live {:doc \"the same scene with an nREPL on the phone (dev builds only)\"\n"
       "        :task (ios-tools/exit-with (ios-tools/live! \".\" " (pr-str (live-ns entry)) "))}"
       (if (has-tests? entry)
         (str "\n  test {:doc \"this scene's tests\"\n"
              "        :task (ios-tools/exit-with (ios-tools/test! \".\"))}")
         "")
       "}}\n"))

(defn- gallery-bb-edn []
  (str generated-header
       ";; Run the gallery from here with `bb run` or `bb live`, or from the repo root with\n"
       ";; `bb gallery`. UDID names the phone: UDID=<hardware udid> bb run.\n"
       "{:paths [\"../scripts\"]\n"
       " :tasks\n"
       " {:requires ([ios-tools])\n"
       "  run {:doc \"▶ the gallery: every scene behind a two-level menu\"\n"
       "       :override-builtin true\n"
       "       :task (ios-tools/exit-with (ios-tools/run! \".\" \"" demo-ns ".gallery.app\"))}\n"
       "  live {:doc \"the gallery with an nREPL on the phone (dev builds only)\"\n"
       "        :task (ios-tools/exit-with (ios-tools/live! \".\" \"" demo-ns ".gallery.live\"))}\n"
       "  test {:doc \"the registry checks and the gallery smoke test\"\n"
       "        :task (ios-tools/exit-with (ios-tools/test! \".\"))}}}\n"))

(defn- bb-edn-with-tasks
  "bb.edn's text with the block between the markers replaced, or nil when the
  markers are missing."
  [text entries]
  (let [b (str/index-of text begin-marker)
        e (some-> b (->> (str/index-of text end-marker)))]
    (when (and b e)
      (let [named (remove (comp fixed-tasks :name) (projects entries))]
        (str (subs text 0 (+ b (count begin-marker)))
             (str/join (for [{:keys [name desc]} named]
                         (str "  " name
                              " {:doc " (pr-str (str "▶ " (or desc name)))
                              " :task (exit-with (run-scene " (pr-str name) "))}\n")))
             (subs text e))))))

;; --- sources

(defn- app-clj [entry]
  (str generated-header
       "(ns " (app-ns entry) "\n"
       "  \"" (:title entry) " as an app of its own: the scene full screen, with no menu and no Back.\"\n"
       "  (:require\n"
       "   [net.b12n.raylib-ios.runner :as runner]\n"
       "   [" (scene-ns entry) " :as scene]\n"
       "   [" (scene-ns entry) ".draw]))\n"
       "\n"
       "(defn -main [& _]\n"
       "  (runner/run! (scene/scene)))\n"))

(defn- live-clj [entry]
  (str generated-header
       "(ns " (live-ns entry) "\n"
       "  \"" (:title entry) " as a dev app: the same scene, with an nREPL listening on the phone.\"\n"
       "  (:require\n"
       "   [net.b12n.raylib-ios.runner.live :as live]\n"
       "   [" (scene-ns entry) " :as scene]\n"
       "   [" (scene-ns entry) ".draw]))\n"
       "\n"
       "(defn -main [& _]\n"
       "  (live/live-run! (scene/scene)))\n"))

(defn- alias-of [entry] (seg entry))

(defn- registry-clj [entries]
  (let [reqs (sort-by first
                      (concat
                       (for [e entries] [(scene-ns e) (str "[" (scene-ns e) " :as " (alias-of e) "]")])
                       (for [e entries] [(str (scene-ns e) ".draw") (str "[" (scene-ns e) ".draw]")])))]
    (str generated-header
         "(ns " demo-ns ".gallery.registry\n"
         "  \"Every scene in the gallery, and the categories that group them.\n"
         "\n"
         "  Requiring this namespace loads every scene and every draw namespace, so each\n"
         "  draw-scene! method is registered. Hello is raylib-ios's own and comes from\n"
         "  that dependency; the rest come from the sub-projects listed in demos.edn.\"\n"
         "  (:require\n"
         (str/join "\n" (for [[_ r] reqs] (str "   " r)))
         "))\n"
         "\n"
         "(def scenes\n"
         "  [" (str/join "\n   " (for [e entries] (str "(" (alias-of e) "/scene)"))) "])\n"
         "\n"
         "(def categories\n"
         "  [" (str/join "\n   "
                         (for [[id title] categories]
                           (str "{:id :" id "\n    :title " (pr-str title) "\n    :scenes ["
                                (str/join "\n             " (map #(str/join " " %)
                                                                 (partition-all 6 (for [e entries :when (= id (:category e))] (str ":" (seg e))))))
                                "]}")))
         "])\n")))

(defn- gallery-app-clj []
  (str generated-header
       "(ns " demo-ns ".gallery.app\n"
       "  \"The gallery as an app: every scene behind a two-level menu.\n"
       "\n"
       "  The registry namespace loads every scene and draw namespace. The menu itself is\n"
       "  raylib-ios's gallery shell.\"\n"
       "  (:require\n"
       "   [" demo-ns ".gallery.registry]\n"
       "   [net.b12n.raylib-ios.gallery :as gallery]))\n"
       "\n"
       "(defn -main [& _]\n"
       "  (gallery/-main))\n"))

(defn- gallery-live-clj []
  (str generated-header
       "(ns " demo-ns ".gallery.live\n"
       "  \"The gallery as a dev app, with an nREPL listening on the phone.\"\n"
       "  (:require\n"
       "   [" demo-ns ".gallery.registry]\n"
       "   [net.b12n.raylib-ios.live :as live]))\n"
       "\n"
       "(defn -main [& _]\n"
       "  (live/-main))\n"))

(defn- check-clj [entries]
  (let [nss (sort (concat [(str demo-ns ".gallery.app")] (map app-ns (projects entries))))]
    (str generated-header
         "(ns " demo-ns ".check\n"
         "  \"Headless compile-check (`jolt -M:check` from the repo root).\n"
         "\n"
         "  Requires every scene's app namespace and the gallery's, which loads each scene\n"
         "  and draw namespace WITHOUT opening a window. It does not run a frame; the\n"
         "  gallery smoke test does that over stubbed raylib.\"\n"
         "  (:require\n"
         (str/join "\n" (for [n nss] (str "   [" n "]")))
         "))\n"
         "\n"
         "(defn -main [& _]\n"
         "  (println \"OK: every app namespace compiled\"))\n")))

;; --- docs

(defn- gallery-md [entries]
  (str "<!-- Generated by `bb gen` from demos.edn. Edits here are overwritten. -->\n"
       "# Scene gallery\n"
       "\n"
       "All " (count entries) " scenes, grouped by category: " (count (projects entries))
       " sub-projects, plus Hello, which lives in raylib-ios. Each name links to the\n"
       "scene's own sub-project, where its page has the description and the source.\n"
       "Build one to a phone with `bb <name>`, or all of them with `bb gallery`.\n"
       (str/join
        (for [[id title] categories
              :let [ds (filter #(= id (:category %)) entries)]]
          (str "\n## " title " (" (count ds) ")\n"
               (str/join
                (for [{:keys [name desc home]
                       :as e} ds]
                  (str "\n### " (if home
                                  (str (:title e) " (in raylib-ios)")
                                  (str "[" (:title e) "](" repo-url "/tree/main/" name ")")) "\n\n"
                       (when desc (str (str/upper-case (subs desc 0 1)) (subs desc 1) "."
                                       (if home
                                         " It is raylib-ios's own proof scene, so it has no sub-project here.\n\n"
                                         (str " Build it with `bb " (if (fixed-tasks name) (str "run " name) name) "`.\n\n"))))
                       (when-let [m (media-of e)] (str "![" (:title e) "](../images/" m ")\n"))))))))))

;; --- main

(defn- fail! [& msg]
  (binding [*out* *err*] (println (apply str msg)))
  (System/exit 1))

(defn- scene-dirs-on-disk []
  (sort (for [d (fs/list-dir root)
              :let [name (str (fs/file-name d))]
              :when (and (fs/directory? d)
                         (not (non-scene-dirs name))
                         (not (str/starts-with? name "."))
                         (seq (fs/glob (fs/file d scene-path) "*.{clj,cljc}")))]
          name)))

(defn -main [& args]
  (let [check? (some #{"--check"} args)
        entries (edn/read-string (slurp (fs/file root "demos.edn")))
        ps (projects entries)
        listed (set (map :name ps))
        on-disk (set (scene-dirs-on-disk))
        by-seg (into {} (map (juxt seg identity)) entries)
        bb-edn (fs/file root "bb.edn")
        bb-text (bb-edn-with-tasks (slurp bb-edn) entries)
        per-scene (for [e ps
                        :let [deps (scene-deps e by-seg)
                              d (:name e)
                              app-dir (str d "/" scene-path "/" (stem e))]
                        [path content] [[(str d "/deps.edn") (scene-deps-edn e deps)]
                                        [(str d "/bb.edn") (scene-bb-edn e)]
                                        [(str app-dir "/app.clj") (app-clj e)]
                                        [(str app-dir "/live.clj") (live-clj e)]]]
                    [(fs/file root path) content])
        gallery-src (str "gallery/src/" demo-path "/gallery/")
        outputs (concat
                 [[(fs/file root "deps.edn") (root-deps-edn entries)]
                  [(fs/file root (str "src/" demo-path "/check.clj")) (check-clj entries)]
                  [bb-edn bb-text]
                  [(fs/file root "gallery/deps.edn") (gallery-deps-edn entries)]
                  [(fs/file root "gallery/bb.edn") (gallery-bb-edn)]
                  [(fs/file root (str gallery-src "registry.clj")) (registry-clj entries)]
                  [(fs/file root (str gallery-src "app.clj")) (gallery-app-clj)]
                  [(fs/file root (str gallery-src "live.clj")) (gallery-live-clj)]
                  [(fs/file root "docs/guide/demos.md") (gallery-md entries)]]
                 per-scene)]
    (when-let [missing (seq (sort (remove on-disk listed)))]
      (fail! "In demos.edn with no scene sources: " (str/join " " missing)))
    (when-let [unlisted (seq (sort (remove listed on-disk)))]
      (fail! "Scene directories missing from demos.edn: " (str/join " " unlisted)))
    (when-let [missing (seq (for [e ps
                                  :let [f (str (fs/file root (scene-dir e)))]
                                  :when (not (and (or (fs/exists? (str f ".cljc")) (fs/exists? (str f ".clj")))
                                                  (fs/exists? (str f "/draw.clj"))))]
                              (:name e)))]
      (fail! "No scene namespace (or no draw.clj) for: " (str/join " " missing)))
    (when-not bb-text
      (fail! "bb.edn has lost its BEGIN/END per-scene task markers"))
    (when-let [clash (seq (filter fixed-tasks listed))]
      (println "No task of their own (name taken by a bb.edn task):" (str/join " " clash)))
    (let [stale (for [[f content] outputs
                      :when (not= content (when (fs/exists? f) (slurp f)))]
                  [f content])]
      (doseq [[f content] stale]
        (println (if check? "out of date:" "updated:") (str (fs/relativize root f)))
        (when-not check?
          (fs/create-dirs (fs/parent f))
          (spit f content)))
      (println (str (count entries) " scenes (" (count ps) " sub-projects), " (count stale) " file(s) "
                    (if check? "out of date" "changed")))
      (when (and check? (seq stale))
        (fail! "Run `bb gen` and commit the result.")))))

(when (= *file* (System/getProperty "babashka.file"))
  (apply -main *command-line-args*))
