;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.camera2d.live
  "2D Camera as a dev app: the same scene, with an nREPL listening on the phone."
  (:require
   [net.b12n.raylib-ios.runner.live :as live]
   [net.b12n.raylib-ios.scenes.camera2d :as scene]
   [net.b12n.raylib-ios.scenes.camera2d.draw]))

(defn -main [& _]
  (live/live-run! (scene/scene)))
