;; Generated by `bb gen` from demos.edn. Edits here are overwritten.
(ns net.b12n.raylib-ios.scenes.blendmodes.live
  "Blend Modes as a dev app: the same scene, with an nREPL listening on the phone."
  (:require
   [net.b12n.raylib-ios.runner.live :as live]
   [net.b12n.raylib-ios.scenes.blendmodes :as scene]
   [net.b12n.raylib-ios.scenes.blendmodes.draw]))

(defn -main [& _]
  (live/live-run! (scene/scene)))
